# ##############################################################################
# ./docker-compose.yml
#
# Copyright 2018. John David Hall
# ##############################################################################

version: '3'
services:
    dst-master:
        build: .
        networks:
            - dst-lan
        volumes:
            - dst-data:/home/dst/.klei/DoNotStarveTogether/
        ports:
            - 10998:10998/udp
        environment:
            - SHARD=Master
            - CLUSTER=DTHDST01
        stdin_open: true
        tty: true

    dst-caves:
        build: .
        networks:
            - dst-lan
        volumes:
            - dst-data:/home/dst/.klei/DoNotStarveTogether/
        ports:
            - 10999:10999/udp
        links:
           - dst-master
        environment:
            - SHARD=Caves
            - CLUSTER=DTHDST01

volumes:
    dst-data:

networks:
    dst-lan:
