version: '3'
services:
    master:
        build: .
        volumes:
            - dst-data:/home/steam/.klei/DoNotStarveTogether/
        ports:
            - 10999:10999/udp
        environment:
            - SHARD=Master
            - CLUSTER=KDST101
        stdin_open: true
        tty: true

    caves:
        build: .
        volumes:
            - dst-data:/home/steam/.klei/DoNotStarveTogether/
        ports:
            - 10998:10998/udp
        links:
           - master:master
        environment:
            - SHARD=Caves
            - CLUSTER=KDST101
        stdin_open: true
        tty: true

volumes:
    dst-data:
